#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: bash scripts/init_llm_kb_repo.sh <target-dir>" >&2
  exit 1
fi

target_dir="$1"

mkdir -p \
  "$target_dir/raw/inbox" \
  "$target_dir/raw/web" \
  "$target_dir/raw/notes" \
  "$target_dir/raw/papers" \
  "$target_dir/raw/repos" \
  "$target_dir/raw/datasets" \
  "$target_dir/raw/images" \
  "$target_dir/wiki/sources" \
  "$target_dir/wiki/outputs" \
  "$target_dir/wiki/_indexes" \
  "$target_dir/.llm-kb"

write_if_missing() {
  local path="$1"
  local content="$2"

  if [[ -e "$path" ]]; then
    return 0
  fi

  printf '%s\n' "$content" > "$path"
}

write_if_missing "$target_dir/wiki/_indexes/sources.md" "# Sources Index

Generated by the plugin. Rebuild with \`kb_rebuild_indexes\` after compiling source notes."

write_if_missing "$target_dir/wiki/_indexes/outputs.md" "# Outputs Index

Generated by the plugin. Rebuild with \`kb_rebuild_indexes\` after archiving output notes."

write_if_missing "$target_dir/.llm-kb/manifest.json" '{
  "schema_version": 1,
  "vault_root": "REPLACE_WITH_ABSOLUTE_VAULT_PATH",
  "sources": {}
}'

write_if_missing "$target_dir/.llm-kb/runs.jsonl" ""

echo "Initialized knowledge base scaffold at: $target_dir"
